# Generated by Django 4.1.2 on 2022-10-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacher", name="address",),
        migrations.RemoveField(model_name="teacher", name="mobile",),
        migrations.RemoveField(model_name="teacher", name="profile_pic",),
        migrations.RemoveField(model_name="teacher", name="salary",),
        migrations.RemoveField(model_name="teacher", name="status",),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
