# Generated by Django 4.1.2 on 2022-10-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_remove_teacher_address_remove_teacher_mobile_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacher", name="email",),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.CharField(default="uviniiii", max_length=40),
        ),
        migrations.AddField(
            model_name="teacher",
            name="mobile",
            field=models.CharField(default="fgh", max_length=20),
        ),
        migrations.AddField(
            model_name="teacher",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pic/Teacher/"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="salary",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
