# Generated by Django 4.1 on 2022-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="qna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Question", models.CharField(max_length=100)),
                ("Option1", models.CharField(max_length=100)),
                ("Option2", models.CharField(max_length=100)),
                ("Option3", models.CharField(max_length=100)),
                ("Correct", models.CharField(max_length=100)),
            ],
        ),
    ]
