# Generated by Django 4.1 on 2022-10-05 09:20

from email.policy import default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="create",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Instructions", models.CharField(max_length=250)),
                ("Passcode", models.CharField(max_length=4)),
            ],
        ),
    ]
