# Generated by Django 3.0.5 on 2022-10-06 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20221006_0531'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='question',
        #     name='course',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='marks',
        # ),
        # migrations.RemoveField(
        #     model_name='quiz',
        #     name='Name',
        # ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='quiz', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3')], max_length=200),
        ),
        # migrations.DeleteModel(
        #     name='Course',
        # ),
    ]
