# Generated by Django 3.0.5 on 2022-10-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_auto_20221006_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
