# Generated by Django 3.0.5 on 2022-10-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_remove_question_option4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Name',
        ),
    ]
