# Generated by Django 4.1.2 on 2022-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz", "0013_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="id",
            field=models.AutoField(primary_key=True, serialize=True),
        ),
    ]
