# Generated by Django 4.1.2 on 2022-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_alter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
