# Generated by Django 4.2.2 on 2023-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0022_result_qcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
