# Generated by Django 4.1.2 on 2022-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="mobile",),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
