# Generated by Django 4.1.2 on 2022-10-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
