# Generated by Django 4.1.2 on 2022-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_remove_student_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="id",),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
