# Generated by Django 4.2.2 on 2023-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rate Between 1 to 7'),
        ),
    ]
