# Generated by Django 4.2.2 on 2023-10-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
